#this files is required for GAE - Google Application Engine (PaAS) deployment
runtime: python37
api_version: 1.0

handlers:
    # {optional .. if doesn't work remove them}
    # This handler routes all requests not caught above to your main app
    # It is required when static routes are defined, but can be omitted 
    # .. when there are no static files defined
- url: /.*
  script: auto
